name: Android APK Builder
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install system dependencies
      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            python3-pip python3-venv build-essential \
            cython3 libffi-dev openssl-dev \
            zlib1g-dev autoconf automake libssl-dev \
            git unzip openjdk-11-jdk

      # 4. Set up Python environment
      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install buildozer cython==0.29.33 virtualenv

      # 5. Initialize Buildozer
      - name: Prepare Buildozer
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
            echo "Created new buildozer.spec"
          else
            echo "Using existing buildozer.spec"
          fi

      # 6. Build the APK
      - name: Build Android APK
        run: |
          buildozer -v android debug 2>&1 | tee build.log
          ls -la bin/ || echo "No bin directory yet"

      # 7. Upload results
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build.log
