name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          
      - name: Cache Buildozer directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
          
      - name: Build with Buildozer
        run: |
          # Your build commands here
