name: Android APK Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            python3-pip python3-venv build-essential \
            cython3 libffi-dev openssl-dev \
            zlib1g-dev autoconf automake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install buildozer cython virtualenv

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
            echo "Created new buildozer.spec"
          else
            echo "Using existing buildozer.spec"
          fi

      - name: Show environment info
        run: |
          python --version
          pip list
          buildozer --version

      - name: Build APK
        run: |
          buildozer -v android debug 2>&1 | tee build.log
          
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: build.log
