name: Android APK Builder
on:
  push:
    branches: [ main ]

# Fixes upload-artifact permission error
permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      # ======================
      # 1. SETUP (NO ARTIFACT DEPENDENCIES)
      # ======================
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ======================
      # 2. SYSTEM DEPENDENCIES
      # ======================
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            python3-pip python3-venv build-essential \
            cython3 libffi-dev openssl-dev \
            zlib1g-dev autoconf automake libssl-dev \
            git unzip openjdk-11-jdk

      # ======================
      # 3. PYTHON ENVIRONMENT
      # ======================
      - name: Set up Python tools
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install buildozer cython==0.29.33 virtualenv

      # ======================
      # 4. BUILD CONFIGURATION
      # ======================
      - name: Initialize Buildozer
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
            echo "New buildozer.spec created"
          else
            echo "Existing buildozer.spec detected"
          fi

      # ======================
      # 5. BUILD PROCESS
      # ======================
      - name: Build APK (Debug)
        run: |
          buildozer -v android debug 2>&1 | tee build.log
          echo "Build complete. APK should be in bin/"

      # ======================
      # 6. ARTIFACT HANDLING (FIXED PERMISSIONS)
      # ======================
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
          retention-days: 1

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: build.log
          retention-days: 1
